title: 'Mother Tongue Languages Symposium 2019'
description: Description
url: 'https://www.mtls.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    School1:
        output: true
    School2:
        output: true
    School3:
        output: true
resources_name: resource-room
favicon: /images/favicon-isomer.ico
google-analytics: UA-124401955-1
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
