title: Mother Tongue Languages Symposium 2019
title-abbreviated: Mother Tongue Languages Symposium 2019
description: >- # this means to ignore newlines until "baseurl:"
  Description
url: "https://www.mtls.sg" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: false
homepage_careers: true


# FAQ URL
faq_url: "/faq/"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"


collections:
  left-nav-one:
    output: true
  left-nav-two:
    output: true
  left-nav-three:
    output: true
resources_name: resource-room
